language: node_js
node_js: '8'

before_install:
  - stty cols 80

dist: trusty
sudo: required

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable fluxbox

services:
  - docker

cache:
  directories:
    - node_modules

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.17.1
    - DOCKER_ENV=$([ "$TRAVIS_BRANCH" == "prod" ] && echo "prod" || echo "stage")
    - DOCKERFILE=Dockerfile-$DOCKER_ENV
    - COMMIT=${TRAVIS_COMMIT::8}
    - TAG=$TRAVIS_BRANCH
    - MAIN_REPO=https://github.com/boheepark/ezasdf.git
    - USERS=ezasdf-users
    - USERS_REPO=${MAIN_REPO}#${TRAVIS_BRANCH}:services/users
    - USERS_DB=ezasdf-users_db
    - USERS_DB_REPO=${MAIN_REPO}#${TRAVIS_BRANCH}:services/users/project/db
    - CLIENT=ezasdf-client
    - CLIENT_REPO=${MAIN_REPO}#${TRAVIS_BRANCH}:services/client
    - SWAGGER=ezasdf-swagger
    - SWAGGER_REPO=${MAIN_REPO}#${TRAVIS_BRANCH}:services/swagger
    - REPO=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    - REACT_APP_USERS_SERVICE_URL=http://127.0.0.1
    - TEST_URL=http://127.0.0.1
    - SECRET_KEY=secret
    - DISPLAY=:99.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - docker-compose -f docker-compose-stage.yml up -d --build

script:
  - bash test.sh $DOCKER_ENV

after_success:
  - bash docker-push.sh
  - bash docker-deploy-stage.sh

after_script:
  - docker-compose -f docker-compose-stage.yml down
