version '3.4'

services:

  users-db:
    container_name: users-db
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  users-service:
    container_name: users-service
    build:
      context: ./services/users
      dockerfile: Docker-stage
    expose:
      - '5000'
    environment:
      - SECRET_KEY=secret
      - APP_SETTINGS=project.config.StagingConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_stage
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db
    links:
      - users-db

  swagger:
    container_name: swagger
    build:
      context: ./services/swagger
      dockerfile: Dockerfile-stage
    ports:
      - '3008:8080'
    environment:
      - API_URL=swagger.json
    depends_on:
      - users-service

  nginx:
    container_name: nginx
    build: ./services/nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - users-service
      - client
    links:
      - users-service
